# Directories
dataset_dir: /home/noorvir/datasets/gqcnn/dexnet_mini_ucl/
cache_dir: /home/noorvir/datasets/gqcnn/cache/
summary_dir: /home/noorvir/datasets/
checkpoint_dir: /home/noorvir/tf_models/GUAN-t/checkpoints/
model_dir: /home/noorvir/tf_models/GUAN-t/pre_trained/         # path to trained GUAN-t model

dataset_config: /home/noorvir/catkin_ws/src/grasp_ucl/cfg/datasets.yaml
pt_weights_filename: /home/noorvir/tf_models/AlexNet/bvlc_alexnet.npy

# Training parameters
queue_capacity: 100                     # TODO
num_epochs: 20
batch_size: 50
optimiser: adam                         # adam, momentum or rmsprop
loss: xentropy                          # l2, xentropy or sparse
val_frequency: 1000                     # steps
log_frequency: 100
save_frequency: 5000

train_frac: 0.8                         # fraction of data to use for training vs validation


# GUAN-t architecture
architecture:
  img_width: 227
  img_height: 227
  img_channels: 3
  num_classes: 6
  retrain_layers:                       # layers of AlexNet to retrain
    - conv5
    - fc6
    - fc7
    - fc8
  skipped_layers:                       # layers of AlexNet to discard
    -
  momentum_rate: 0.001
  learning_rate: 0.001                  # TODO
  exponential_decay: 0                  # use learning-rate decay - 0 or 1
